language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode9

before_install:
  - gem install xcpretty
  - gem install fastlane

script:
  - fastlane test

after_success:
  - bash <(curl -s https://codecov.io/bash)
